### ISSUE TITLE
[Feature]: Add ability to pass target folder in the config file

### ISSUE THREAD

**Issue by vyahello** [myint/rstcheck#105]
### To Dos

- [x] I have checked the [issues](https://github.com/myint/rstcheck/issues) and think that this is not a duplicate.

- [X] I added a very descriptive title to this issue.

### Description

According to `load_configuration_from_file` function, there is no option to set target folder check in `.rstcheck.cfg` or `setup.cfg` file.
 
For example,  it would be great to set folder path/include patterns in the config file:
```ini
[rstcheck]
path=docs
# or something like
patterns=docs1/*.rst, docs2/*.rst
```

Consequently, the user will have two options: set it via cli param and config file.

### Operating System

macOS

### Python Version

Python 3.8.13

### rstcheck Version

5.0.0

**Comment by Cielquan** [comment]
First off the code base currently is being reworked (#104) and any feature request will have to wait until it is finished.

But the behavior you are describing is still present.

___

I currently cannot think of a linting tool, where you can set the files you want to check in a config file.

And IMO this is not a good idea to implement this feature generally but especially for rstcheck.

Well first of the CLI would need to have priority over the config file. Sure.

Because you need to call the command anyways why not specify the target you want the command to run against in the same call? I guess most people run such tool automated anyways, so there you could fix the file names.

And the more important part is that in rstcheck we don't only use one config file. If you do not specify a config file via `--config` rstcheck automatically looks for a config file in you cwd and loads it as its main config. But for each file is checks in also checks if a config file was set and if not it will again look for an additional config file in the directory of the file it is currently checking. And if there is none it looks up the directory tree for one. If it reaches the root directory and does not find one is runs with the main config + defaults. So when we allow to specify paths in the config file this would add a lot of overhead and work.

But I am open for discussion. What I can imagine to support as a feature would be the opposite: ignore files.

**Comment by Cielquan** [comment]
I will close the issue. If you want to further discuss this topic feel free to reopen it.
