### ISSUE TITLE
Detect and reject markdown-style links in RST

### ISSUE THREAD

**Issue by jayvdb** [myint/rstcheck#32]
At coala we've found it quite common for people to accidentally use markdown syntax links in RST, and no tool currently detects this, and reviewers also dont pick it up.

**Comment by myint** [comment]
One approach to adding the check could be to implement a [`visit_paragraph()`](http://epydoc.sourceforge.net/docutils/private/docutils.nodes.SparseNodeVisitor-class.html) in [`CheckTranslator`](https://github.com/myint/rstcheck/blob/7f4125d9e469e81608ce4bbc2cb06931581009f6/rstcheck.py#L625). That would give all the information needed. This would be simpler than going through the raw RST file since `visit_paragraph()` would exclude the code blocks, which could theoretically contain valid Markdown code (`.. code:: markdown`).

In terms of outputting warnings in `CheckTranslator`, I think it would involve calling [`self.document.reporter.warning('warning message', base_node=node)`](https://github.com/docutils-mirror/docutils/blob/e88c5fb08d5cdfa8b4ac1020dd6f7177778d5990/docutils/writers/manpage.py#L682).

**Comment by myint** [comment]
This is closed by #35.

@biscuitsnake Do you need to submit the work for review on the [GCI task](https://codein.withgoogle.com/dashboard/task-instances/6647168846790656/)? I ask because I don't see an "Approve task" link. Thanks.
